apiVersion: "koudingspawn.de/v1"
kind: Vault
metadata:
  name: {{ .Values.secretName }}
  labels:
{{ include "pull-secret-vault.labels" . | indent 4 }}
spec:
  path: {{ .Values.path }}
  type: "DOCKERCFG"
  dockerCfgConfiguration:
  {{- toYaml .Values.dockerCfgConfiguration | nindent 4 }}